### ISSUE TITLE
Not working on firefox

### ISSUE THREAD

**Issue by diguifi** [tiny-devs/tiny-dungeon-online#119]
Reddit reported "TouchEvent not defined."

**Comment by nico-abram** [comment]
After some quick googling, I think the fix might look something like this: https://github.com/tiny-devs/tiny-dungeon-online/commit/30f285c531b9a70f317a646f9eeadff8374778e4

**Comment by diguifi** [comment]
It worked! I'll just fix some deploy errors caused by a new version of Deno and then publish it. Thank you very much @nico-abram

**Comment by nico-abram** [comment]
Great! Glad I could help. Sorry I didn't submit a pull request, I didn't have a chance to test it

**Comment by diguifi** [comment]
No problem! It's deployed.
