### ISSUE TITLE
Performance issues in the new version of the game

### ISSUE THREAD

**Issue by andredarcie** [tiny-devs/tiny-dungeon-online#18]
Testing the game in the current version that uses Deno runtime and native web sockets.
I found performance problems in simple tests like moving the character on the screen quickly, it ends up crashing the server.

These are the deploys I tested:
[Old version on Nodejs and socket io](https://tiny-dungeon-online.herokuapp.com/)
[New verison on Deno and native web sockets](https://diguifi-tests-tiny-mmo.herokuapp.com/)

**Comment by FabriDamazio** [comment]
We need work on a binary data transfer solution.

**Comment by diguifi** [comment]
I checked how much data was being transfered and noticed that sending pure stringfied objects, in some cases, causes over 140.000 Bytes of data *per movement* to all sockets, and this increases for each player logged in.

@FabriDamazio found [this](https://medium.com/samsung-internet-dev/being-fast-and-light-using-binary-data-to-optimise-libraries-on-the-client-and-the-server-5709f06ef105) amazing article that covers the best strategy for this situation: arrayBuffers, they convert arrays of data into bytes, sending way less data.

We really should implement this approach.
