### ISSUE TITLE
Optimize canvas rendering

### ISSUE THREAD

**Issue by andredarcie** [tiny-devs/tiny-dungeon-online#28]
- ~Use offscreen Canvas~ (since we are not rendering images, this is not useful)
- [x] Use multiple layered canvases
```
  <canvas id="ui-layer" width="480" height="320"></canvas>
  <canvas id="game-layer" width="480" height="320"></canvas>
  <canvas id="background-layer" width="480" height="320"></canvas>
```
- [x] Render screen differences only, not the whole new state (validate viability).

Links:
[Improving HTML5 Canvas Performance](https://www.html5rocks.com/en/tutorials/canvas/performance/)

**Comment by diguifi** [comment]
[cool article](http://diveintohtml5.info/canvas.html)
