### ISSUE TITLE
Add eight-direction movement

### ISSUE THREAD

**Issue by andredarcie** [tiny-devs/tiny-dungeon-online#86]
![image](https://user-images.githubusercontent.com/7493330/92182162-612ea600-ee21-11ea-87a8-b5607f3e249c.png)

![image](https://user-images.githubusercontent.com/7493330/92182268-a9e65f00-ee21-11ea-87db-9fdadc2d3660.png)

**Comment by diguifi** [comment]
bro this would require a massive change in code logic and, to me, it doesn't feel thaaat necessary.  
currently we send "up, down, right, left" commands to the server and theres a lot of checks for each movement, this would require 4 new directions and 4 new blocks of checks, I think it's too much to go through for not much of a change.  
I'll be closing this issue for now, but if you come with a simple solution for this, please feel free to comment it and we might reopen this discussion and the possibility to implement this feature!
