### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by diguifi** [tiny-devs/tiny-dungeon-online#88]
We need to document the entire process of contribution, From setup and execution, to a pull request

**Comment by andredarcie** [comment]
I agree! This is very important

**Comment by diguifi** [comment]
![workspace](https://user-images.githubusercontent.com/31022286/96666342-4bbbff80-132d-11eb-8975-a5a15add2137.gif)

**Comment by diguifi** [comment]
![tiny land](https://user-images.githubusercontent.com/31022286/106227466-fc0c9000-61c7-11eb-875e-b1b16aa6425e.png)

**Comment by diguifi** [comment]
![image](https://user-images.githubusercontent.com/31022286/106367461-97654880-6321-11eb-90e2-95115cb54c66.png)

**Comment by diguifi** [comment]
![image](https://user-images.githubusercontent.com/31022286/106393173-642fc180-63d4-11eb-9d09-3ce998b9cb72.png)
![image](https://user-images.githubusercontent.com/31022286/106393482-1a47db00-63d6-11eb-8cb3-fcfa3ae5022d.png)
![image](https://user-images.githubusercontent.com/31022286/106393540-6f83ec80-63d6-11eb-867a-6c0f60bd961d.png)
![image](https://user-images.githubusercontent.com/31022286/106393822-ea013c00-63d7-11eb-91e2-3592c541305c.png)

**Comment by diguifi** [comment]
![image](https://user-images.githubusercontent.com/31022286/106525863-66bd1480-64c3-11eb-9615-d4430ff5da01.png)

```ts
import { Npcs } from '../../../Enums.ts'
import NpcBase from '../npcBase.ts'

export default class LonelyMan extends NpcBase {
    constructor() {
        super(Npcs.CityOldMale2, false, 'lonelyman', 0, 0, 0, 0, 1000, 0, 0, 36, null, [], null)
    }
}
```

**Comment by diguifi** [comment]
![image](https://user-images.githubusercontent.com/31022286/106829866-bd655280-666b-11eb-8e70-4d722b251384.png)
